name: Inserir Dados Automático

on:
  schedule:
    - cron: '15 2 * * *'  # 23:15 no Brasil
  workflow_dispatch:

jobs:
  rodar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - run: pip install psycopg2-binary

      - run: python inserir_dados.py
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
